export const users = { id: 'id' }
export const students = { id: 'id', studentId: 'studentId', createdAt: 'createdAt' }
export const studentSkills = { studentId: 'studentId', skillId: 'skillId' }
export const skills = { id: 'id', name: 'name' }
export const projects = { id: 'id', studentId: 'studentId' }
export const certifications = { id: 'id', studentId: 'studentId' }
export const applications = { id: 'id', studentId: 'studentId', jobId: 'jobId' }
export const jobs = { id: 'id', companyId: 'companyId' }
export const companies = { id: 'id' }
export const mockInterviews = { id: 'id', studentId: 'studentId', createdAt: 'createdAt' }
export const interviewMessages = { id: 'id', interviewId: 'interviewId' }
export const roadmaps = { id: 'id', studentId: 'studentId' }
export const roadmapSteps = { id: 'id', roadmapId: 'roadmapId' }
export const resumes = { id: 'id', studentId: 'studentId' }
export const resumeVersions = { id: 'id', studentId: 'studentId' }
export const userScores = { id: 'id', studentId: 'studentId' }
export const recommendations = { id: 'id', studentId: 'studentId' }
export const notifications = { id: 'id', userId: 'userId' }
export const analyticsEvents = { id: 'id', userId: 'userId' }
