export const users = { id: 'id', email: 'email', role: 'role', createdAt: 'createdAt', updatedAt: 'updatedAt' }
export const students = { id: 'id', studentId: 'studentId', name: 'name', slug: 'slug', bio: 'bio', primarySkill: 'primarySkill', resumeUrl: 'resumeUrl', githubUsername: 'githubUsername', skillVector: 'skillVector', createdAt: 'createdAt' }
export const studentSkills = { studentId: 'studentId', skillId: 'skillId', proficiency: 'proficiency' }
export const skills = { id: 'id', name: 'name', category: 'category' }
export const projects = { id: 'id', studentId: 'studentId', title: 'title', description: 'description', url: 'url', startDate: 'startDate', endDate: 'endDate' }
export const certifications = { id: 'id', studentId: 'studentId', name: 'name', issuer: 'issuer', issueDate: 'issueDate', credentialUrl: 'credentialUrl' }
export const applications = { id: 'id', studentId: 'studentId', jobId: 'jobId', status: 'status', matchScore: 'matchScore', createdAt: 'createdAt' }
export const jobs = { id: 'id', companyId: 'companyId', title: 'title', description: 'description', location: 'location', salaryRange: 'salaryRange', jobType: 'jobType', status: 'status', createdAt: 'createdAt' }
export const jobSkills = { jobId: 'jobId', skillId: 'skillId', requiredProficiency: 'requiredProficiency' }
export const companies = { id: 'id', name: 'name', companyName: 'companyName', industry: 'industry' }
export const mockInterviews = { id: 'id', studentId: 'studentId', role: 'role', score: 'score', feedback: 'feedback', status: 'status', createdAt: 'createdAt' }
export const interviewMessages = { id: 'id', interviewId: 'interviewId', role: 'role', content: 'content', createdAt: 'createdAt' }
export const roadmaps = { id: 'id', studentId: 'studentId', targetRole: 'targetRole', progress: 'progress' }
export const roadmapSteps = { id: 'id', roadmapId: 'roadmapId', title: 'title', status: 'status', order: 'order' }
export const resumes = { id: 'id', studentId: 'studentId', fileUrl: 'fileUrl', status: 'status' }
export const resumeVersions = { id: 'id', studentId: 'studentId', jobTitle: 'jobTitle', content: 'content' }
export const userScores = { id: 'id', studentId: 'studentId', overallScore: 'overallScore' }
export const recommendations = { id: 'id', studentId: 'studentId', type: 'type', title: 'title' }
export const notifications = { id: 'id', userId: 'userId', type: 'type', title: 'title', isRead: 'isRead' }
export const analyticsEvents = { id: 'id', userId: 'userId', eventType: 'eventType', createdAt: 'createdAt' }
export const experience = { id: 'id', studentId: 'studentId', title: 'title', company: 'company' }
export const education = { id: 'id', studentId: 'studentId', school: 'school', degree: 'degree' }
